
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/cygdrive/c/Users/GillV/AppData/Local/JetBrains/CLion2024.3/cygwin_cmake/share/cmake-3.30.5/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: CYGWIN - 3.5.5-1.x86_64 - x86_64
...
